apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btr-log-parser-logs
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: btr-nginx-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi