apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nginx-volume
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-volume
  type: NodePort
status:
  loadBalancer: {}
